# Generated by Django 3.2.5 on 2021-07-24 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_feet', models.IntegerField()),
                ('height_inches', models.IntegerField()),
                ('current_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('goal_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('current_BMI', models.IntegerField()),
                ('goal_BMI', models.IntegerField()),
                ('current_blood_pressure_dia', models.IntegerField()),
                ('current_blood_pressure_sys', models.IntegerField()),
                ('goal_blood_pressure_dia', models.IntegerField()),
                ('goal_blood_pressure_sys', models.IntegerField()),
                ('cureent_blood_sugar', models.IntegerField()),
                ('goal_blood_sugar', models.IntegerField()),
                ('goal_daily_calories', models.IntegerField()),
                ('goal_carbs_grams', models.IntegerField()),
                ('goal_proteins_grams', models.IntegerField()),
                ('goal_fats_grams', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Flog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('meal_type', models.CharField(max_length=1)),
                ('name', models.CharField(max_length=50)),
                ('servings', models.DecimalField(decimal_places=2, max_digits=5)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Elog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('distance_miles', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reps_laps', models.IntegerField()),
                ('weight_pounds', models.DecimalField(decimal_places=2, max_digits=5)),
                ('intensity', models.IntegerField()),
                ('pace_minutes_per_mile', models.IntegerField()),
                ('calories_burned', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.userprofile')),
            ],
        ),
    ]
