# Generated by Django 3.2.4 on 2021-07-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elog',
            name='name',
            field=models.CharField(default='running', max_length=50),
        ),
    ]
