# Generated by Django 3.2.4 on 2021-07-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_elog_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='elog',
            name='length_of_time',
            field=models.IntegerField(default=0),
        ),
    ]
