# Generated by Django 3.2.4 on 2021-07-23 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_elog_length_of_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elog',
            old_name='user_id',
            new_name='user',
        ),
    ]
