# Generated by Django 3.2.4 on 2021-07-23 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_user_id_elog_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flog',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_id',
            new_name='user',
        ),
    ]
